import os
from os import path

script_location = path.dirname(__file__)
shared_build_gradle = path.join(script_location, "../shared.build.gradle.kts")
root_folder = path.normpath(path.join(script_location, "../.."))
loaders_folder = path.join(root_folder, "src/loaders")

with open(shared_build_gradle) as file:
    build_gradle_content = file.read()

generated_by_script_note = "This file was generated by script. You should not modify it as it will be overwritten on next script run"

def write_build_gradle(file: str, content: str):
    print(f"Writing {file}")
    with open(file, "w+") as f:
        f.write(f"// {generated_by_script_note}\n// If you need to modify build.gradle.kts - check /environment directory in root of your project\n\n{content}")

def write_build_gradle_gitignore(dir: str):
    file = path.join(dir, ".gitignore")
    print(f"Writing {file}")
    with open(file, "w+") as f:
        f.write(f"# {generated_by_script_note}\n\nbuild.gradle.kts\n")

for loader in os.listdir(loaders_folder):
    loader_folder = path.join(loaders_folder, loader)
    if not path.isdir(loader_folder): continue
    for version in os.listdir(loader_folder):
        version_folder = path.normpath(path.join(loader_folder, version))
        if not path.isdir(version_folder): continue

        build_gradle_file = path.join(version_folder, "build.gradle.kts")
        write_build_gradle(build_gradle_file, build_gradle_content)
        write_build_gradle_gitignore(version_folder)
